name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5.3
  - ipywidgets=8.0.6 
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=22.0.4
  - pandas-profiling=3.6.3
  - pyarrow=10.0.1
  - pip:
      - wandb==0.15.2