name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.3.1
  - python=3.10.10
  - ipython=8.13.2
  - notebook=6.5.4
  - jupyterlab=3.5.3
  - cookiecutter=2.1.1
  - hydra-core=1.3.2
  - matplotlib=3.7.1
  - pandas=1.5.3
  - git=2.40.1
  - pip=23.1.2
  - pip:
      - wandb==0.15.2